#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6164-webs
    bind *:80
    mode http
    balance roundrobin
    server 6164-web-02 54.152.146.93:80 check
    server 6164-web-01 54.174.105.9:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
