#!/usr/bin/env bash
# Installing nginx on a server and configuring a simple server
sudo apt-get install nginx -y

# Create the index.html file
echo "Holberton School" > /var/www/html/index.html

# Create a new server block configuration file
sudo touch /etc/nginx/sites-available/default

# Configure the server block
cat << EOF | sudo tee /etc/nginx/sites-available/default
server {
  listen 80;
  index index.html;
  root /var/www/html;

  # Add any additional server configurations here (optional)
}
EOF

# Enable the new server block
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx service
sudo service nginx restart
