#!/usr/bin/env bash
# Installing Nginx on Ubuntu
# Nginx is listening on port 80
# The GET request should return a page containing "Holberton School"

# Update the package index and upgrade installed packages
sudo apt-get update -y
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create a custom HTML page
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

# Exit script
exit 0
